gpt2
Oneflow-Inc/CoModels pull request #29
Opened 2023-10-23 03:11 UTC by Drlifei

增加了新的gpt2模型

2023-10-23 06:57 UTC, zkyseu approved these changes

2023-10-23 07:05 UTC, ShawnXuan requested changes
文件都多了一级目录，比如：
```
 
nlp/libai/gpt2/gpt2/gpt2_infer_config.py
```

2023-10-23 08:08 UTC, Drlifei commented
目录的问题修改好了

2023-10-24 02:03 UTC, ShawnXuan approved these changes

2023-10-24 02:03 UTC, merged